name: Build

on:
  push:
    branches:
      - master
    tags:
      - "*"
      - "!**-alpha**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 500

      - name: Package & Release
        uses: BigWigsMods/packager@master
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
